apiVersion: v1
kind: Pod
metadata:
  name: postgis
spec:
  containers:
    - env:
        - name: ALLOW_IP_RANGE
          value: 0.0.0.0/0
        - name: POSTGRES_DB
          value: gis
        - name: POSTGRES_PASS
          value: docker
        - name: POSTGRES_USER
          value: docker
      image: kartoza/postgis:11.0-2.5
      livenessProbe:
        exec:
          command:
            - exit 0
      name: postgis
      ports:
        - containerPort: 5432
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgis-data
  restartPolicy: OnFailure
  volumes:
    - name: postgis-data
      persistentVolumeClaim:
        claimName: postgis-data
